### PR TITLE
add Fedora support

### PR DESCRIPTION
**Pull request by juliandunn**
Some of the tests are failing for lack of a `sox` package. I'm not sure why this is required in a base install?

### CODE REVIEW

**Comment by benlangfeld** [comment]
I'll look into the sox thing. A couple of issues:
1. Merge commits to master made it in here. Could you rebase atop the develop branch? We follow git-flow on our cookbooks.
2. I don't see anything placing the systemd definition. Is this not intended to be used?

**Comment by benlangfeld** [comment]
So, we're testing for sox [because it's used by Asterisk to mix down recordings](https://github.com/mojolingo/asterisk-cookbook/commit/8fc13e23029bd5406c7b5b8daa9aabed8f72ff5a); call recording fails without it.

I'm also seeing test failures on `package-fedora-20` due to Asterisk not being started.

**Comment by juliandunn** [comment]
- Rebased atop `develop`.
- I removed the dangling systemd commit; not sure how that made it in there.
- So the reason the "Asterisk started" serverspec tests are failing is because `net-tools` is not on the Fedora Bento boxes and so netstat can't be run;  something I started [fixing](https://github.com/opscode/bento/commit/84b12a7c475b21ebface66ceaff1cc80ea070a88)
- As for `sox`, I'm wondering how the tests are passing on, for instance, CentOS 6.5 now? Because if you install only the `asterisk` and `asterisk-devel` packages on that platform, they don't install Sox.

**Comment by benlangfeld** [comment]
> Rebased atop develop.
> I removed the dangling systemd commit; not sure how that made it in there.

Thanks :)

> So the reason the "Asterisk started" serverspec tests are failing is because net-tools is not on the Fedora Bento boxes and so netstat can't be run; something I started fixing

Should this dependency not be explicitly declared by this cookbook?

> As for sox, I'm wondering how the tests are passing on, for instance, CentOS 6.5 now? Because if you install only the asterisk and asterisk-devel packages on that platform, they don't install Sox.

I presume sox is present in the base box already. Again, we should depend explicitly on sox.

**Comment by juliandunn** [comment]
> > So the reason the "Asterisk started" serverspec tests are failing is because net-tools is not on the Fedora Bento boxes and so netstat can't be run; something I started fixing
> > Should this dependency not be explicitly declared by this cookbook?

No, because you only need `netstat` for the tests. One other answer would be to write a fixture cookbook inside this cookbook that explicitly installs it before you run the tests?

> I presume sox is present in the base box already. Again, we should depend explicitly on sox.

I doubt it, since the baseboxes install just the base OS, but I'll add `sox` as a dependency to all the package arrays as well.

**Comment by juliandunn** [comment]
@benlangfeld This is complete now - all tests pass.

**Comment by benlangfeld** [comment]
Thanks @juliandunn. I'll run the tests to double check then merge this today :)

**Comment by benlangfeld** [comment]
`package-centos-65` has these failures. Are they related?

```
         1) asterisk Port "5060" should be listening
            On host ``
            Failure/Error: it { should be_listening.with('tcp') }
       netstat -tunl | grep -- \^tcp\ .\*:5060\
       expected Port "5060" to be listening
            # /tmp/busser/suites/serverspec/localhost/asterisk_spec.rb:15:in `block (3 levels) in <top (required)>'

         2) asterisk Port "5060" should be listening
            On host ``
            Failure/Error: it { should be_listening.with('udp') }
       netstat -tunl | grep -- \^udp\ .\*:5060\
       expected Port "5060" to be listening
            # /tmp/busser/suites/serverspec/localhost/asterisk_spec.rb:16:in `block (3 levels) in <top (required)>'
```

**Comment by juliandunn** [comment]
@benlangfeld so... this is why I was asking you if these tests ever passed. Because in the current state, even before I added Fedora support, they didn't.

The reason is because on RHEL, the Digium RPMs drop off Asterisk that doesn't have a `modules.conf`. Because there's no `modules.conf`, none of the modules are autoloaded, which means `chan_sip.so` isn't loaded. If `chan_sip.so` isn't loaded, there won't be a SIP listener on 5060.

I'm going to suggest that we change this cookbook to use the EPEL packages for Asterisk at least on CentOS / RHEL platforms, 'cause that's what people would expect. In fact, I'll push that commit to this branch now.

**Comment by benlangfeld** [comment]
I had thought that the tests were passing, but our CI build does not run periodically and can be somewhat unstable with leftover VMs. I'd build our cookbooks on DigitalOcean via Travis if it wasn't going to cost hundreds of dollars a month.

Why would the Digium RPMs install Asterisk in a crippled fashion? I don't see that documented, is it not a bug? Do you have an upstream reference?

I'm happy to default to EPEL packages, since using Digium's repos is disabled on all distros by default and I gather CentOS without EPEL is basically useless (I'm not a CentOS guy really). I would however like for it to be possible to enable the Digium repos, and note that there be dragons.

**Comment by juliandunn** [comment]
If you do `rpm -ql` on the Asterisk packages from Digium, there is no `modules.conf`.
It's not technically a broken configuration; using SIP and having a listener on port 5060 is not a mandatory setup, that's just what you've defined as success criteria in the acceptance test suite. So we can change the test suite -- that would be another solution.

Can you give me guidance on what you'd like to see?

**Comment by benlangfeld** [comment]
I'd like to see `node['asterisk']['package']['repo']['enable']` respected on CentOS, but for EPEL packages to be used by default. I don't want to prevent Digium packages from being used, though I'm not particularly interested in the nuances of which modules are considered mandatory by Digium's packaging.

**Comment by benlangfeld** [comment]
Sorry for the slow response @juliandunn, Github doesn't send notifications of new commits and I wasn't polling this PR.

**Comment by benlangfeld** [comment]
Closed by 73323806305b7d48ad391c978eea53f3ff48b105

**Comment by benlangfeld** [comment]
Released in v1.1.0. Apologies for the delay, and thanks for the contribution, much appreciated :)

**Pull request closed without merging**
